// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Signy Play",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Signy Play",
            targets: ["AppModule"],
            bundleIdentifier: "com.Seodongwon.SSC",
            teamIdentifier: "U6CCD5BT22",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "카메라를 사용합니다.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources"),
                .copy("MLFile/MyHandPoseClassifier.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)
